version: '3'

services:
  ebook:
    image: asciidoctor/docker-asciidoctor
    volumes:
      - .:/documents/
    command: scripts/docker-startup.sh
    network_mode: bridge
  
  travis:
    build:
      context: .
      dockerfile: ./docker/travis/Dockerfile
    volumes:
      - .:/app
      - ./.travis:/root/.travis
    network_mode: bridge
  
  npm:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - .:/app
    network_mode: bridge
